Repository amwebexpert/guess_the_text, pull requests merged in 2022-07, with the labels that each got.

#71 fix: map json serialization names
  README.md
  lib/features/categories/api.category.model.dart
  lib/features/categories/api.category.model.freezed.dart
  lib/features/categories/api.category.model.g.dart
  lib/features/categories/category.icons.map.dart
Labels: bug

#72 docs: update and re-structure
  README.md
  docs/flutter_service_worker.js
  docs/index.html
  docs/main.dart.js
  docs/sections/coding-standards/naming.md
  docs/sections/coding-standards/patterns.md
  docs/sections/coding-standards/store.md
  docs/sections/coding-standards/tests.md
  docs/sections/references.md
  lib/l10n/app_en.arb
  lib/l10n/app_fr.arb
Labels: documentation

#70 feat: author list
  lib/features/about/app.version.table.widget.dart
  lib/features/about/author.info.table.widget.dart
  lib/features/about/card.widget.dart
  lib/features/about/contributor.model.dart
Labels: enhancement

#73 feat: persist selected category
  lib/features/game/game.store.dart
  lib/services/storage/shared.preferences.enum.dart
Labels: enhancement
