Repository amwebexpert/guess_the_text, pull requests merged in 2022-06, with the labels that each got.

#6 feat: memoize played items
  .github/pull_request_template.md
  README.md
  docs/sections/completed-subjects.md
  lib/documents.repository.dart
  lib/features/game/game.played.items.storage.service.dart
  lib/features/game/game.screen.dart
  lib/features/game/game.store.dart
  lib/features/game/game.store.g.dart
  lib/features/game/letters.widget.dart
  lib/service.locator.dart
  lib/theme/widgets/snackbar/snackbar.utils.dart
  lib/theme/widgets/snackbar/snackbar.widget.dart
  pubspec.lock
  pubspec.yaml
  test/features/categories/categories.screen_test.mocks.dart
Labels: enhancement

#46 docs: Test coverage explanation
  README.md
Labels: documentation

#50 fix: async code trying to update unmounted widget state
  lib/features/about/about.screen.dart
  lib/features/about/app.version.table.widget.dart
  lib/features/about/platform.info.table.widget.dart
  lib/features/game/game.image.intro.widget.dart
  lib/features/game/game.image.widget.dart
  lib/features/game/letters.widget.dart
  lib/theme/widgets/animations/horizontal.slide.intro.widget.dart
  lib/theme/widgets/animations/scaling.intro.widget.dart
Labels: bug

#58 style: responsive QR Code screen
  lib/features/game/challenge/chalenge.qr.landscape.layout.dart
  lib/features/game/challenge/chalenge.qr.portrait.layout.dart
  lib/features/game/challenge/on.the.fly.chalenge.qr.screen.dart
  lib/features/game/challenge/on.the.fly.chalenge.widget.dart
  lib/route.generator.dart
Labels: enhancement
